const router = require('express').Router()
const categoryRouter = require('./category.route')
const productRouter = require('./product.route')
const supplierRouter = require('./supplier.route')
const customerRouter = require('./customer.route')
const purchaseOrderRouter = require('./purchase-order.route')
const exportOrderRouter = require('./export-order.route')
const authRouter = require('./auth.route')
const analyticdRouter = require('./analytic.route')
const reportRouter = require('./report.route')


router.use('/auth',authRouter)
router.use('/analytic',analyticdRouter)
router.use('/report',reportRouter)
router.use('/category',categoryRouter)
router.use('/product',productRouter)
router.use('/supplier',supplierRouter)
router.use('/customer',customerRouter)
router.use('/purchase-order',purchaseOrderRouter)
router.use('/export-order',exportOrderRouter)
module.exports = router